spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  mail:
    host: smtp.mailtrap.io
    port: 465
    username: 1f4c14d004808c
    password: 34a7bbfe76e6e2
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/nospace
    driver-class-name: org.postgresql.Driver
    username: glaze

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

profile-picture:
  base-url: http://localhost:8080/api/account/profile-picture/
  default-picture-url: http://localhost:8080/api/account/profile-picture/default.png

drive:
  zip-temporal-container: /home/glaze/go/temp/
  max-default-capacity: 1073741824
  base-path: /home/glaze/go/
  picture-storage: /home/glaze/go/ppf/

server:
  servlet:
    context-path: /api

jwt:
  properties:
    expiration-in-days: 2
    prefix: Bearer
    secret-key: SomeSuperSecretKeyImpossibleToGuessByAnyoneInThisEntireUniverseSomeSuperSecretKeyImpossibleToGuessByAnyoneInThisEntireUniverseSomeSuperSecretKeyImpossibleToGuessByAnyoneInThisEntireUniverseSomeSuperSecretKeyImpossibleToGuessByAnyoneInThisEntireUniverse